# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
install! 'cocoapods', :disable_input_output_paths => true

target 'TQIBankDIO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TQIBankDIO
  
  pod 'TQICoordinator', :git => 'https://github.com/vafreitas/ios-mod-coordinator.git'

  target 'TQIBankDIOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TQIBankDIOUITests' do
    # Pods for testing
  end

end
